### ISSUE TITLE
Improve our support for MSE and make it spec-compliant

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/Pale-Moon#1033]
I'm creating this to track the progress of updating our current MSE code to be more spec compliant and provide better MSE support. Things that need done (not necessarily in this order):

- [x] Implement state machinery to reduce raceyness of our media code (both current and new).
- [x] Research and make necessary changes (if any) to Stagefright/MoofParser to work with new code.
- [x] Research and make necessary changes to the MediaFormatReader and our decoders (if needed).
- [x] Abstact the TrackBuffer interface to make it easier to update the surrounding code.
- [x] Make MediaPromises work together with lambdas.
- [x] Implement Completion MediaPromises and MediaPromise::All
- [x] Rewrite our TrackBuffer/SourceBuffer code according to spec.
- [x] Add a new (mostly) spec-compliant MediaSourceDemuxer object (behind a pref) that will work together with the MediaFormatReader. This will be the bulk of our new MSE-specific code.
- [x] Research if any additional areas of our MSE code need to be aligned to the spec.
- [x] Optimize new architecture to prevent performance regressions.
- [x] Fix remaining regressions (such as stalls when changing resolutions, a/v desync issues, etc).
- [x] Enable new MediaSourceDemuxer by default.

Targeting the 27.3.0 release, but may have to be pushed back depending on amount of time needed to get all this working.

**Comment by trav90** [comment]
Point 1 was fixed by #1028. Point 4 was completed by #916.

**Comment by wolfbeast** [comment]
I'm going to bump remaining open issues to 27.4 -- 27.3 needs to be published next week somewhere due to some sec issue deadlines; we'll just have to consider this an ongoing effort for now.

**Comment by trav90** [comment]
Agreed. Based on the research I've been doing overnight, I think getting this done for 27.4 is doable and should be the target.

**Comment by trav90** [comment]
Added point 5 to list above. While not directly needed, by allowing MediaPromise to use lambdas there will be less reverse-engineering required for the actual MSE patches.

**Comment by wolfbeast** [comment]
Marking point 5 done since I've tested it on Windows (BBC news, YT, Twitch, Vimeo) with #1066 in, and seems to play fine.

One glaring issue we still have is twitch streams having terrible video/audio de-sync.

**Comment by wolfbeast** [comment]
Also, it's not entirely clear for testing if I need to flip a pref or not for testing... If so, which one?

**Comment by trav90** [comment]
Marking point 2 complete also (#1056).

I'm still aware of the issue with Twitch. Most of the recent media PR's should improve a/v de-sync issues, but haven't resolved whatever Twitch is doing yet. Our new code will also include some A/V sync fixes (plan on tackling that this weekend).

Everything competed here so far applies to the whole media subsystem or is MP4 specific. Only the MSE-specific rewrite (the MediaSourceDemuxer object) will be behind a pref that will need flipped for testing once it's implemented (I've updated the top comment to hopefully clarify that).

**Comment by trav90** [comment]
After working on this literally the entire weekend it looks like our new MSE code is dependent on changes made to MediaPromises that have not yet been ported to our tree. I've added point 6 to the first comment to reflect that.

**Comment by wolfbeast** [comment]
Sorry to hear it's such a headache. I've merged the changes in and marked point 6 completed. I'll give it a test later today.

**Comment by trav90** [comment]
> Sorry to hear it's such a headache.

No worries. An undertaking as massive as this one is bound to cause a few headaches along the way.  :smile: 

Headaches aside, progress is being made and we are getting there!

**Comment by trav90** [comment]
The initial implementation of our new TrackBuffer/SourceBuffer code (point  7) was merged in #1081.

**Comment by trav90** [comment]
The base implementation of the MediaSourceDemuxer landed in #1091.

**Comment by THEtomaso** [comment]
This is a good site to test the MSE freezing issues..
Live broadcasts @ NRK.no:
https://tv.nrk.no/direkte/
With MSE enabled, the picture freezes very often.
With MSE disabled, it plays just fine.

I've tested it on three different computers, using Pale Moon v27.3.0 and v27.4.0a1(2017-05-10)

Only thing is that the service is probably region locked.
I don't know for sure though, so you'll just have to give it a try.

**Comment by wolfbeast** [comment]
@THEtomaso Although I understand you'd love to see your Norwegian TV-through-browser improved, they are usuallynot the best to use for testing. **We should focus on globally used services before local services.**

Also, you're correct about the region locking, which isn't a surprise.
> NRK har ikke rettigheter til å vise direktesendinger utenfor Norge.

**Comment by trav90** [comment]
Point 3 should (mostly) be taken care of by #1099 and #1102, so marking that point complete.

Also added points to the list for performance and regression issues.

**Comment by trav90** [comment]
Point 10 above fixed by #1116.

**Comment by THEtomaso** [comment]
Here's another site to test MSE issues at:
http://screenrant.com/video/10-new-star-wars-theories-that-actually-make-sense/

With MSE enabled, the videos will stop buffering at some point during playback, and the loading wheel will just start to spin.
With MSE disabled, the videos plays just fine.

Tested with Pale Moon v27.3.0,x64 and v27.4.0a1,x86(2017-05-27)

**Comment by wolfbeast** [comment]
Tested the star wasr video with the latest patches in, no problem. Also, I still get the shutdown crash if I watch multiple sites or for a longer time using MSE. Still no chance presented itself to catch the browser shutdown state with a debugger before the deliberate watchdog crash happens.

**Comment by THEtomaso** [comment]
I wish that there were some kind of version labeling on the download page, so we wouldn't have to download these unstable builds blindly all the time.

**Comment by THEtomaso** [comment]
I just gave v27.4.0a1,x86(2017-05-28) a try, and this build doesn't seem to be affected by ANY of the issues that I've previously reported with MSE!:

* No more momentarily freezes during video playback at aftonbladet.se, nrk.no and vgtv.no.
(nrk.no and vgtv.no were fixed in a previous unstable build, while aftonbladet.se was fixed in this latest one)

* No more buffering problems for videos at screenrant.com.

Although, I did run into a problem that I haven't encountered before..
When watching a live stream at nrk.no, I got a "Pale Moon has stopped working" error message.
Strangely enough, I was able to simply close this message, without having PM crash on me.
..but of course, this is an unstable build, so it might not be very serious.

Anyway, it's nice to see that all the hard work that you guys have put into this (especially trav90) has payed off so well!! :)

**Comment by trav90** [comment]
Point 11 seems to be fixed by #1122, so marking complete.
Our new code has been enabled by default in #1123 for testing, but am not going to mark point 12 as complete just yet until we get more feedback from users.

**Comment by trav90** [comment]
> Also, I still get the shutdown crash if I watch multiple sites or for a longer time using MSE

At this point this gets top priority as it should be a blocker for shipping this in -release.

**Comment by wolfbeast** [comment]
Unfortunately #1124 didn't fix the shutdown hang. I attached a debugger during the hang, but didn't get anything out of it. It doesn't seem to happen if I don't mix old and new since I tried playing with 4 sites while not touching the pref and leaving it on and there was no shutdown hang, but that _will_ mean it's a problem to dynamically switch between the two types (for WebM)... :disappointed: 

I also noticed that with the new format reader, it's not possible to jump to specific locations in vimeo videos (ok with the old reader). Clicking on the play bar briefly jumps the cursor to where it is supposed to be, then right back to where it was playing. You can only play start to finish.

**Comment by trav90** [comment]
> It doesn't seem to happen if I don't mix old and new

This explains why I have not been able to reproduce on Linux; I hadn't been flipping the prefs during my testing.

> that will mean it's a problem to dynamically switch between the two types (for WebM)

Yup. I'll give this some thought on the best way to handle.

> it's not possible to jump to specific locations in vimeo videos

Confirmed. I'll look into it.

**Comment by wolfbeast** [comment]
Trunk build today hung again on shutdown after playing videos on several sites, without touching the format-reader pref, so my previous assertion was wrong; it does happen when just using the new reader.

**Comment by trav90** [comment]
Yeah, I finally encountered it myself late last night while testing some other things. I'm working on it.

**Comment by trav90** [comment]
I finally managed to reproduce this hang with a debugger attached and got a [backtrace](https://gist.github.com/trav90/937d999ee7cad8945fa47487b02ea030) for it.

**Comment by wolfbeast** [comment]
Looks like the hang is more reliably reproducible with the latest patches in. I think the vimeo issue is also at the root of something else I've noticed; if a YT video starts with an advert, you can't skip the advert (it will just keep playing) so there's something wrong with scripted setting of playback position in media, by the looks of it.

**Comment by wolfbeast** [comment]
#1140 seems to resolve the YT advert issue :+1:

**Comment by sergeevabc** [comment]
@trav90, thank you for scrupulous efforts to resolve video issues.

**Comment by mattatobin** [comment]
@trav90 While YouTube at large seems to be resolved the YouTube Live streams are very hit and miss on if they work with the new format reader.

It may or may not have to do with Streams that are Monetized and have pre-roll ads. Some streams work fine while others, when the new format reader is enabled, will sit there on a single frame and show and endless throbber.

Please check it out.

**Comment by trav90** [comment]
I think there are 2 core reasons causing the hang here: the media-related threads are not getting properly shutdown (Mozilla also encountered this, and I will have patches to this effect tomorrow), and that wonderful reentrant monitor again (due to the asynchronicity of our new MSE code).

> Looks like the hang is more reliably reproducible with the latest patches in.

Likely due to me disabling TailDispatch for the new MSE (a change which I will probably be reverting soon).

> ... Please check it out.

I think I might know the problem here. Will look into it.

**Comment by trav90** [comment]
#1171 fixes the shutdown hang we've seen. Known remaining issues at this time with the new code:

Seeking does not work outside the buffered area on Vimeo.
Some YouTube live streams stall (endless throbber)
WebM is not supported (new code must be disabled).

I will start working on these three issues this weekend.

**Comment by wolfbeast** [comment]
Please note that for me, Vimeo doesn't seek either way, doesn't matter if it is in the buffered range or not.

**Comment by trav90** [comment]
Noted.

**Comment by THEtomaso** [comment]
Seeking @ Vimeo.com works just fine with the latest stable build though (v27.3.0), with both MSE enabled and disabled.
Only the unstable build seems to be affected by this issue.

**Comment by trav90** [comment]
@THEtomaso The unstable build is currently using entirely different code for MSE playback. Hence the issues that aren't present in current release.

**Comment by THEtomaso** [comment]
I know.
Just thought that the information might be useful, in case you weren't aware of it.

**Comment by wolfbeast** [comment]
Possibly Vimeo also hung up on the same spec compliance thing that troubled coub, because with the current unstable I can seek into videos without problem.
Ad-supported live streams on YT also play and resume after ads now.

So that just leaves WebM to tackle. This is a good state, since WebM is disabled by default anyway, and I'm happy to publish it in its current state for 27.4 if WebM will take more time. Still waiting to get sec bug access so that is currently the time-determining factor.

**Comment by trav90** [comment]
That's interesting as I still experience the seeking issue on Vimeo (just checked).

WebM is certainly going to take a bit more time and should not be a blocker for 27.4 (27.5 would be a more reasonable target).

**Comment by wolfbeast** [comment]
Gah, scratch that. I had the pref flipped from a previous test. Sorry! Will re-test.

**Comment by wolfbeast** [comment]
Re-testing with the PROPER config confirms Vimeo and the ad-interrupted live streams on YT are both still an issue with the new format reader.

**Comment by wolfbeast** [comment]
If it helps, I found that video on vimeo that doesn't buffer (short vids like https://vimeo.com/50366872) don't exhibit the issue, while buffering ones (longer videos) do...

**Comment by trav90** [comment]
Thanks. I believe I have found the fix for Vimeo. Will be testing and hopefully submitting a pull request later today.

**Comment by trav90** [comment]
I have updated the first comment to reflect where we stand on this. We are now (mostly) spec compliant and the shutdown hang has been resolved so we can leave the new code enabled by default, so both those points have been checked off. I also unchecked point 11 until we can fix the last couple remaining regressions (one of which will hopefully be fixed later today).

**Comment by wolfbeast** [comment]
Good timing on completion of this then, because I'm working through the sec cycle (while also updating UXP so it's a bit slower this time around) and that means we can move to a relbranch after that.

**Comment by trav90** [comment]
I may have spoke too soon. With some local patches I can seek on Vimeo now, however playback will then stall after seeking. I am still working on it...

**Comment by trav90** [comment]
I think the cause of the remaining regressions here is that our new MSE code is almost entirely async (per spec), which is causing a race condition or similar somewhere else in the core media subsystem. This makes it difficult to track down the cause. I have set aside several hours over the upcoming holiday weekend where I will be working on this. I _will_ have an update on where we stand by early next week.

**Comment by wolfbeast** [comment]
Okay. Thanks once again for your work on this and being decidedly persistent on getting to the bottom of this. Async is a real pain for something as complex as media, but I guess the people writing the spec didn't think past the advantages that it would give them (in terms of protecting their streams from leeching)

**Comment by THEtomaso** [comment]
I came across this "MSE Conformance Tests" page, which you might find usefull:
https://yt-dash-mse-test.commondatastorage.googleapis.com/unit-tests/2017.html
..unless you're already aware of it of course.

**Comment by trav90** [comment]
At the risk of once again speaking too soon here's an update on where I'm at on this:

I've been working on this the entire weekend so far and the work I've done does appear to verify that it is indeed a race condition that we're dealing with here. I've been working on some local patches and initial testing with them looks promising, though they need some more testing/work before being ready to submit a PR. I will be continuing to work on them and will hopefully have a PR ready to submit in the next day or two.

**Comment by wolfbeast** [comment]
I've given the browser a thorough test after #1209 landed and there hasn't been a single instance now where things don't play on Windows (as long as they aren't serving playlists, that is). Youtube, Vine, Vimeo, Twitch, all thoroughly tested, including things like dynamic pop-out-on-scroll etc. All seems to work fine.

**Comment by sergeevabc** [comment]
> WebM is certainly going to take a bit more time and should not be a blocker for 27.4
WebM checkbox would be disabled not to mislead about ability to deliver value or just unchecked as before?

**Comment by trav90** [comment]
WebM is being discussed in #1119.
