### ISSUE TITLE
Create temporary controls for incomplete MSE code.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1212]
See #1119 

We need temporary front-end code **on the release branch only** to make our incomplete WebM support still selectable, but with the trade-off that the new format reader can't be used. To be unambiguous:

- Add a new option for the new format reader
- Make MSE+WebM dependent on the new format reader being off.
- Add browser glue init code that disables MSE+WebM if the new format reader is enabled

This won't prevent situations where people use about:config manually, but that is their own risk of it not working then. Roasted by one of the dragons in there, in that case ;)

**Comment by wolfbeast** [comment]
Solved by 2ece38c86599e351d07d7ab0fdf165591149c665 (this has the string addition) and 15ca33e889c9b3e2faf15c162af75b4a42d704fc

**Comment by JustOff** [comment]
I have two problems with this solution:

1. When I switch "Enable Media Source Extensions (MSE)" off and on, "Enable MSE for WebM video" becomes available to select even if "Enable the new Media Format Reader" is enabled.
2. While "Enable the new Media Format Reader" is correct from the developer point of view, it could be hard to understand to users and it will be even more difficult to translate properly. Could we just call it "Use new MSE library", considering that MSE is already explained above?

**Comment by wolfbeast** [comment]
Follow-up shortly.

**Comment by wolfbeast** [comment]
"new MSE library" might be a bit clearer to the end user but at the same time it's terribly incorrect from a code point of view. It's not a library... At the same time "code" can be ambiguously misread.

I guess the closest description would be "Use MSE asynchronously" -- I trust that that translates well enough, while being true to the changes.

**Comment by JustOff** [comment]
Please clarify does this means "Handle MSE asynchronously" or "Call MSE asynchronously"?

**Comment by wolfbeast** [comment]
Neither. It means "Use it in an asynchronous way"

**Comment by JustOff** [comment]
Thanks. I've updated the project on CrowdIn and made the announcement on the forum.

**Comment by wolfbeast** [comment]
Thank you for being on the ball. I know it's relatively short term for these.

**Comment by JustOff** [comment]
Sorry, but I found one more minor problem that arose after https://github.com/MoonchildProductions/Pale-Moon/commit/95ac85345579345540ab313393e8d86c52c2992a: when "Use MSE asynchronously" is not selected, then switching off "Enable Media Source Extensions (MSE)" do not disable "Enable MSE for WebM video" checkbox.

**Comment by wolfbeast** [comment]
gah.

**Comment by wolfbeast** [comment]
I should have drawn a flowchart first for this. Anyway, should be all fixed now.

**Comment by JustOff** [comment]
Unfortunately it's still not enough :sweat_smile: 

I guess we should also remove `onsyncfrompreference="gContentPane.updateMSEWebM();"` from `checkbox id="videoMSENFR"` otherwise it's always enable "Enable MSE for WebM video" checkbox when "Use MSE asynchronously" is not enabled.

**Comment by wolfbeast** [comment]
Right, upon opening the preferences. I usually don't use the "onsyncfrom" events, myself, copy-pasta mistake.

**Comment by JustOff** [comment]
Don't blame yourself for "copy-pasta", that call was required before https://github.com/MoonchildProductions/Pale-Moon/commit/95ac85345579345540ab313393e8d86c52c2992a landed. And finally it seems everything works as expected, but I understand your feelings :wink:

**Comment by trav90** [comment]
Sorry that this turned into a bit of a headache for you. I've tested this and it all appears to be working correctly except for one possible issue: if the user already has MSE + WebM selected, at first start WebM is disabled in favor of the async option. While in most cases this would be desirable (from the standpoint of the users actually using the new code and getting all the benefits of it), some users may not appreciate having their preferences changed at first startup after updating.

STR: create a new profile with 27.3.0, and check the MSE + WebM option. Then open this new profile with 27.4.0RC1 and look at the MSE preferences again.

**Comment by wolfbeast** [comment]
I've done this on purpose. The defaults will be enforced in that respect.

Some users will not appreciate it because "how dare I change *their* settings blah blah high tower, others (probably more) will have set WebM enabled to work around current issues and would be best served with this automatic change. I do plan to mention it in the release notes.

**Comment by trav90** [comment]
Sounds good. I absolutely agree 100% that the new defaults should be enforced in this way. Just wanted to make mention of it. :+1:
